### ISSUE TITLE
Rename功能错误

### ISSUE THREAD

**Issue by luckcao** [ErrorCodesForLzx/CloudreveZX#1]
你的FileInfoActivity中的Rename按钮中，组成json的代码有问题。不对。你的代码如下：
requestJsonObj.put("action","rename");
requestJsonObj.put("new_name",etFileNewName.getText().toString());
JSONObject srcJsonObj = new JSONObject();
srcJsonObj.put("dirs",new JSONArray());
JSONArray items = new JSONArray();
items.put(currentEntity.getId());
srcJsonObj.put("items",items);
String responseText = OKHTTPUtil.sendPost(NetworkTrafficUrlBuilder.build(NetworkTrafficRouter.network_rename_file), new HashMap<>(), requestJsonObj, GlobalRunningConfiguration.authentication_cookie_token);
其中，srcJsonObj没有放入requestJsonObj里。也就是加上这么一句话：
requestJsonObj.put("src", srcJsonObj);

哦，对了，还有两点需要说一下，是关于3.8版本的：
1、在加载文件列表时，返回的json有点变动，pic字段名变成了thumb。只要将MainActivity中129行itemEntityObj.setPic(itemJsonObj.getString("pic"));改为itemEntityObj.setPic(itemJsonObj.getString("thumb"));即可。
2、在下载文件时，获取文件的下载url格式有变动，需要在之前加上networkUrl，也就是改成：
bundle.putString("downloadUrl",networkUrl + downloadUrl);

麻烦您更改一下。
谢谢！

**Comment by ErrorCodesForLzx** [comment]
好的 谢谢，到时候去提交
